# Generated by Django 3.1.7 on 2021-03-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_citizen_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='email',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='last_name',
        ),
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
