# Generated by Django 3.1.7 on 2021-03-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210322_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='citizen',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
