# Generated by Django 3.1.7 on 2021-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210322_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='father_citizen_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='husband_citizen_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='mother_citizen_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
